<a href="https://colab.research.google.com/github/JustinCamay-prog/Numerical-Methods/blob/Numerical-Methods/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations
#Justin Anjelo Camay
#201912644

#Addition

In [3]:
import numpy as np

A = np.array([
    [-5,0],
    [4,1],
])
B = np.array([
    [6,-3],
    [2,3],
])
A+B

array([[ 1, -3],
       [ 6,  4]])

#Substraction

In [7]:
import numpy as np
B = np.array([[6,  -3],
       [ 2,  3]])
A = np.array([
    [-5,0],
    [4,1],
]) 
B-A

array([[11, -3],
       [-2,  2]])

In [8]:
import numpy as np
A = np.array([
    [-5,0],
    [4,1],
]) 
B = np.array([[6,  -3],
       [ 2,  3]])
A-B

array([[-11,   3],
       [  2,  -2]])